export default [
    { "quote": "I finally realized that people are prisoners of their phones… so that's why they're called cell phones.", "author": "Unknown" },
    { "quote": "My favorite exercise is a cross between a lunge and a crunch. I call it lunch.", "author": "Unknown" },
    { "quote": "I'm on a new diet. It's called ‘not caring anymore.'", "author": "Unknown" },
    { "quote": "I don't have a bucket list, but my fucket list is a mile long.", "author": "Unknown" },
    { "quote": "I'm great at multitasking. I can waste time, be unproductive, and procrastinate all at once.", "author": "Unknown" },
    { "quote": "My ability to remember song lyrics from 20 years ago is impressive. My ability to remember why I walked into a room is not.", "author": "Unknown" },
    { "quote": "I don't need a mood ring. I have a face.", "author": "Unknown" },
    { "quote": "I'm not avoiding the holidays. I'm just celebrating them very quietly… in another room… with the door closed.", "author": "Unknown" },
    { "quote": "The best thing about December is telling yourself the holiday calories don't count. Science hasn't confirmed it, but my heart has.", "author": "Unknown" },
    { "quote": "I'm not sure if I'm ready for the holidays, but my stretchy pants definitely are.", "author": "Unknown" },
    { "quote": "I'm not sure how many problems I have because math is one of them.", "author": "Unknown" },
    { "quote": "I'm not clumsy. The floor just hates me, the table and chairs are bullies, and the walls get in my way.", "author": "Unknown" },
    { "quote": "Before you marry a person, you should first make them use a computer with slow Internet to see who they really are.", "author": "Will Ferrell" },
    { "quote": "I'm not great at the advice. Can I interest you in a sarcastic comment?", "author": "Chandler Bing" },
    { "quote": "I told my suitcase we're not going anywhere this year. Now it's full of emotional baggage.", "author": "Unknown" },
    { "quote": "Some people wake up early. Some people stay up late. I do both and that's why I'm tired all the time.", "author": "Unknown" },
    { "quote": "I always take life with a grain of salt… plus a slice of lemon and a shot of tequila.", "author": "Unknown" },
    { "quote": "I'm not arguing, I'm just explaining why I'm right.", "author": "Unknown" },
    { "quote": "My wallet is like an onion: opening it makes me cry.", "author": "Unknown" },
    { "quote": "I need a six-month vacation, twice a year.", "author": "Unknown" },
    { "quote": "Common sense is like deodorant. The people who need it most never use it.", "author": "Unknown" },
    { "quote": "I'm on a seafood diet. I see food and I eat it.", "author": "Unknown" },
    { "quote": "Life is short. Smile while you still have teeth.", "author": "Unknown" },
    { "quote": "Of course I talk to myself. Sometimes I need expert advice.", "author": "Unknown" },
    { "quote": "I'm not lazy, I'm on energy-saving mode.", "author": "Unknown" },
    { "quote": "If stress burned calories, I'd be a supermodel by now.", "author": "Unknown" },
    { "quote": "My bed is a magical place where I suddenly remember everything I was supposed to do.", "author": "Unknown" },
    { "quote": "Life update: Currently holding it all together with one bobby pin.", "author": "Unknown" },
    { "quote": "I followed my heart and it led me to the fridge.", "author": "Unknown" },
    { "quote": "Life is too short to fold fitted sheets.", "author": "Unknown" },
    { "quote": "I whisper “what the heck” to myself at least 20 times a day.", "author": "Unknown" },
    { "quote": "Adulthood is just saying “I'll deal with that later” until later becomes never.", "author": "Unknown" },
    { "quote": "Some days you eat salads and go to the gym. Some days you eat cupcakes and refuse to put on pants. It's called balance.", "author": "Unknown" },
    { "quote": "Why do they call it beauty sleep when you wake up looking like a troll?", "author": "Unknown" },
    { "quote": "I'm not superstitious, but I am a little stitious.", "author": "Michael Scott" },
    { "quote": "People say that money is not the key to happiness, but I always figured if you have enough money, you can have a key made.", "author": "Joan Rivers" },
    { "quote": "Before you criticize someone, walk a mile in their shoes. That way, you'll be a mile from them, and you'll have their shoes.", "author": "Jack Handy" },
    { "quote": "The trouble with having an open mind, of course, is that people will insist on coming along and trying to put things in it.", "author": "Terry Pratchett" },
    { "quote": "I love being married. It's so great to find that one special person you want to annoy for the rest of your life.", "author": "Rita Rudner" },
    { "quote": "My therapist told me the way to achieve true inner peace is to finish what I start. So far I’ve finished two bags of M&Ms and a chocolate cake", "author": "Unknown" },
    { "quote": "I'm not lazy. I'm just on my energy saving mode.", "author": "Unknown" },
];
  